### ISSUE TITLE
Migrating this Repository to Voxpupuli

### ISSUE THREAD

**Issue by SimonHoenscheid** [camptocamp/docker-puppet-catalog-diff#2]
Hi Camptocamp Staff, 

Voxpupuli is interested in adopting this repository and maintain the software. 
@yann-soubeyrand and @ckaenzig Raphaël Pinson metioned you might be the right people to ping.

Kind Regards,
Simon

**Comment by yann-soubeyrand** [comment]
Hello @SimonHoenscheid, sorry for the late reply. I’m not the right person, but facing the lack of movement on our side, I’ll try to help you. It seems I cannot do the transfer without the permission to create a public repository on voxpupuli. How did you proceed for the transfer of camptocamp/puppet-catalog-diff-viewer?

**Comment by saimonn** [comment]
Hello, thanks @yann-soubeyrand for reminding me this issue, I totally missed it in the first place. I just transferred this repo to voxpupuli. Please tell us if you still need something on our side.

**Comment by SimonHoenscheid** [comment]
@yann-soubeyrand @saimonn with the repo transfer, the process is finished. Thank you!
